package nl.ind.onderzoek.application;

public enum Beperking {
    ARBEID_ALS_KENNISMIGRANT,
    ARBEID_ALS_NIET_GEPRIVILEGIEERD_MILITAIR_OF_NIET_GEPRIVILEGIEERD_BURGERPERSONEEL,
    ARBEID_ALS_ZELFSTANDIGE,
    ARBEID_IN_LOONDIENST,
    BUITEN_SCOPE,
    GRENSOVERSCHRIJDENDE_DIENSTVERLENING,
    HET_AFWACHTEN_VAN_EEN_VERZOEK_OP_GROND_VAN_ARTIKEL_17_VAN_DE_RIJKSWET_OP_HET_NEDERLANDERSCHAP,
    HET_ZOEKEN_NAAR_EN_VERRICHTEN_VAN_ARBEID_AL_DAN_NIET_IN_LOONDIENST,
    LEREND_WERKEN,
    MEDISCHE_BEHANDELING,
    NIET_TIJDELIJKE_HUMANITAIRE_GRONDEN,
    ONDERZOEK_IN_DE_ZIN_VAN_RICHTLIJN_EU_2016_801,
    OVERPLAATSING_BINNEN_EEN_ONDERNEMING,
    SEIZOENSARBEID,
    STUDIE,
    TIJDELIJKE_HUMANITAIRE_GRONDEN,
    UITWISSELING_AL_DAN_NIET_IN_HET_KADER_VAN_EEN_VERDRAG,
    VERBLIJF_ALS_ECONOMISCH_NIET_ACTIEVE_LANGDURIG_INGEZETENE_OF_ALS_VERMOGENDE_VREEMDELING,
    VERBLIJF_ALS_FAMILIE_OF_GEZINSLID,
    VERBLIJF_ALS_HOUDER_VAN_DE_EUROPESE_BLAUWE_KAART,
    WETENSCHAPPELIJK_ONDERZOEK_IN_DE_ZIN_VAN_RICHTLIJN_2005_71_EG
}